routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::resource('/','indexController');


Route::get('/direccion/{id}','direccionController');


Route::get('/galeria/{id?}','prendasController@mostrar')->name('prendas');

// Route::view('/galeria','prendas')->name('prendas');

// Route::view('/prendaDescripcion','prendaDetails')->name('prendaDetails');

Route::get('/prendaDescripcion/{id?}/{color?}','descripcionController')->name('prendaDescripcion');


Route::get('/contraEntrega','contraEntregaController')->name('contraEntrega')->middleware('verified');


Route::get('/obtenerComentarios/{id?}','getComentariosController')->name('getComentarios');
// Route::get('/contraEntrega')

Route::view('/cart','carrito')->name('carrito');




Route::resource('/resenas','resenasController')->middleware('verified');


Route::get('/compras','comprasController')->name('compras')->middleware('verified');


Route::get('/detalle/{id?}','comprasController@detalles')->name('detalle');





Route::view('/pagoTarjeta','pagoTarjeta')->name('pagoTarjeta');


Route::view('/transferencia','transferencia')->name('transferencia');





// Route::get('/tipoPrenda',function(){
// 	return view('cms.formaPago');
// });


Route::resource('/comentarios','comentariosController');

Route::resource('/talla','tallaController');


Route::resource('/tipoPrenda','tipoPrendaController');


Route::resource('/formaPago','formaPagoController');

Route::resource('/estadoVenta','estadoVentaController');

Route::resource('/ventas','ventasController');





Route::resource('/prenda','prendaController');


Route::resource('/color','colorController');

Route::resource('/imagen','imagenController');




// RUTAS DE CONSULTA

Auth::routes(['verify'=> true]);


Route::get('/dataTalla','dataTallaController');


Route::get('/dataTipo','dataTipoController');


Route::get('/dataColor/{id}','dataColorController');



//FIN RUTAS DE CONSULTA


// Route::view('/tipoPrenda','cms.tipoPrenda')->name('cms.tipoPrenda');

// Route::view('/formaPago','cms.formaPago')->name('cms.formaPago');

// Route::view('/estadosVenta','cms.estadosVenta')->name('cms.estadoVenta');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');




Route::get('/ventasDetalle/{id}','detallesController');

resources/views/comentariosPaginate.blade.php
@forelse($comentarios as $listar)
        <div class="comntarios_usu">
            <div class="usuario">
                <h2>{{$listar->user->name}}</h2>
                <h3>{{$listar->created_at}}</h3>
            </div>
            <div class="usu_comentario">
                <p>
                    {{$listar->comentario}}
                </p>
            </div>

        </div>

@empty

         <div class="usu_comentario">
                <p>
                    no hay comentarios
                </p>
            </div>

@endforelse

resources/views/estadoPedido.blade.php
@extends('layout')





@section('headers')

   <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="css/reset.css">
    <link rel="stylesheet" href="css/footer.css">
    <link rel="stylesheet" href="css/estilos.css">
    <link rel="stylesheet" href="css/navbar.css">

    <link rel="stylesheet" href="css/comentario_prenda/perfil_usuario.css">
    <link rel="stylesheet" href="css/comentario_prenda/estado_pedido.css">
    <link rel="stylesheet" href="css/comentario_prenda/modal_estado.css">

    <script src="js/jquery.min.js"></script>
    <script src="js/all.min.js"></script>
    <script src="js/main.js"></script>


@endsection


@section('main')
  <main>
        <section>
            <div class="usuario_resena">
                <div class="perfil_usuario">
                    <h1>Perfil de usuario</h1>
                    <div>
                        <h2>Usuario:</h2>
                        <h3>Cristian alvarez</h3>
                    </div>
                    <div>
                        <h2>Correo:</h2>
                        <h3>Cristian@gmail.com</h3>
                    </div>
                    <div class="contenedor_bton">
                        <div>
                            <a href="{{route('compras')}}">Comprar</a>
                        </div>
                        <div>
                            <a href="{{route('resenas.index')}}">Reseña</a>
                        </div>
                    </div>
                </div>
                <div class="contenedor_estados">
                    @csrf

                   <div>
                    @forelse($arrayCompras as $listarCompras)
                    <div class="caja_estado">
                        <div class="caja_info">
                            <h1>Estado</h1>
                            <h2>{{$listarCompras->estado->estado}}</h2>
                        </div>
                        <div class="caja_info">
                            <h1>Fecha de Compra</h1>
                            <h2>{{$listarCompras->created_at}}</h2>
                        </div>
                        <div class="caja_info">
                            <h1>Fecha de Entrega</h1>
                            <h2>10/25/26</h2>
                        </div>
                        <div class="caja_info">
                            <h1>Costo Envio</h1>
                            <h2>S/{{$listarCompras->cenv}}</h2>
                        </div>
                        <div class="caja_info">
                            <h1>Formato de Pago</h1>
                            <h2>{{$listarCompras->forma_pago->fpago}}</h2>
                        </div>
                        <div class="caja_info">
                            <h1>Pago Total</h1>
                            <h2>S/{{$listarCompras->totalp}}</h2>
                        </div>
                        <a href="#" key={{$listarCompras->id}} class="comprasDetalle">Ver Detalles</a>
                        @csrf 
                    </div>
                    @empty
                      <div class="caja_estado">
                       NO HAY COMPRAS
                    </div>
                    

                    @endforelse
                    </div>
                    <div>{{$arrayCompras->links() }}</div>
                    
                </div>
                
            </div>
        </section>
        <section class="modal_compra" id="view_modal_compra">
             <a href="#" class="close">X</a>
                <div class="contenedor_galleria">
                       
                        <div style="margin-bottom:15px;border-bottom: 5px solid #B4B4B4 ;padding-bottom:15px;">
                    
                        <div class="contenedor_ropa">
                            <div class="caja_ropa">
                                <img src="img/Ropa/691043_899A08_portrait_HD_1.jpg" alt="">
                            </div>
                            <div class="caja_text">
                                <div class="texto_informacion">
                                    <div class="texto_info">
                                        <h3>Diseño</h3>
                                        <p>Sybilla</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Color</h3>
                                        <p>Plomo</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Talla</h3>
                                        <p>xl</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Precio</h3>
                                        <p>S./599.99</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>cantidad</h3>
                                        <p>25</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Total</h3>
                                        <p>S./599.99</p>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <div class="comentario_resana">
                                <h2>
                                        Reseña y/o Comentario
                                    </h2>
                                    <form action="">
                                        <textarea name="comentario" id="textarea"></textarea>
                                        <button>Agregar</button>
                                    </form>
                        </div>
                  </div>
                   <div style="margin-bottom:20px;">
                    
                        <div class="contenedor_ropa">
                            <div class="caja_ropa">
                                <img src="img/Ropa/691043_899A08_portrait_HD_1.jpg" alt="">
                            </div>
                            <div class="caja_text">
                                <div class="texto_informacion">
                                    <div class="texto_info">
                                        <h3>Diseño</h3>
                                        <p>Sybilla</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Color</h3>
                                        <p>Plomo</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Talla</h3>
                                        <p>xl</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Precio</h3>
                                        <p>S./599.99</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>cantidad</h3>
                                        <p>25</p>
                                    </div>
                                    <div class="texto_info">
                                        <h3>Total</h3>
                                        <p>S./599.99</p>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                        <div class="comentario_resana">
                                <h2>
                                        Reseña y/o Comentario
                                    </h2>
                                    <form action="">
                                        <textarea name="comentario" id="textarea"></textarea>
                                        <button>Agregar</button>
                                    </form>
                        </div>
                  </div>
            </div>
        </section>
    </main>

@endsection


@section('fieldjs')

<script src="js/estado/model.js"></script>

@endsection

resources/views/layout.blade.php
 <!DOCTYPE html>
<html lang="en">
<head>

    @yield('headers')
    
</head>
<body>
  <header>
        <div class="contenedor_navbar">
            <div class="contenedor_animada">
                <ul>
                    <li>
                        <h1 class="h1">US$3 </h1> DESCUENTO DE SU PRIMERA ORDEN
                    </li>
                    <li>
                        <h1 class="h1">US$3 </h1> DESCUENTA DE ROPA DE VERANO
                    </li>
                </ul>
            </div>
            <a href="{{route('index')}}" class="navbar_logo">
                <img src="img/logo.png" alt="Logo">
            </a>
            <input type="checkbox" id="menu_navbar">
            <label for="menu_navbar">
                <img src="img/menu.png" alt="menu">
            </label>
            <nav class="menu_nav">
                <ul class="menu_principal">
                    <li class="menu_lista">
                        <div class="container_1">
                            <form action="" autocomplete="on">
                                <input id="search" name="search" type="text" placeholder="Buscar..." class="search">
                                <input type="submit" id="search_submit" value="Buscar">
                            </form>
                        </div>
                    </li>
                    <li class="menu_lista">
                        <a href="{{ route('prendas')}}">Prendas <img src="img/arrow.png" alt="arrow"></a>
                    </li>
                    <li class="menu_lista sub_cuenta">
                        <a href="#" class="cuenta">Cuenta <span class="fas fa-sort-down"></span></a>
                        <ul class="sub_menu">
                            @guest
                            <li class="menu_lista">
                                <a href="{{route('login')}}">Iniciar Sesion <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                             <li class="menu_lista">
                                <a href="{{route('compras')}}">Compras <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('resenas.index')}}">Reseñas <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            @else

                            <li class="menu_lista">
                                <a href="#"><?php echo explode(" ",Auth::user()->name)[0]; ?> <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('compras')}}">Compras <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('resenas.index')}}">Reseñas <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a  href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Salir
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                            </li>

                            @if(Auth::user()->role=='admin')

                            <li class="menu_lista">
                                <a href="{{route('prendas')}}">Administrar <img src="img/arrow.png" alt="arrow"></a>
                            </li>


                            @endif


                            @endguest
                        </ul>
                    </li>
                    <li class="menu_lista_2">
                        <a href="{{route('carrito')}}">Carrito de Compra <img src="img/arrow.png" alt="arrow"></a>
                    </li>
                    <li class="menu_lista_3">
                        <a href="{{route('carrito')}}"><span class="fas fa-shopping-cart"></span></a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>



            @yield('main')



                <footer>
            <div class="politica">
                    <h1>Politicas de la Tienda</h1> 
                    <br>
                    <article>
                        <ul>
                            <li>Términos y condiciones</li>
                            <li>Horario de Atención</li>
                            <li>Libro de Reclamos</li>
                            <li>Políticas de entrega , garantía y devolución</li>
                        </ul>
                    </article> 
                    <br>   
            </div>
            <div class="tienda">
                    <h1>Información de la Tienda</h1> 
                    <br>
                    <article>
                        <ul>
                            <li>Tienda   Elimar</li>
                            <li>Llámanos ahora al: 951 545 421</li>
                            <li>Email: elimar@gmail.com</li>
                        </ul> 
                    </article>
                    <br>
            </div>
            <div class="redes">
                <h1>Redes Sociales</h1> 
                <br>
                <article>
                    <ul>
                        <li><img src="img/fooder/facebook.png" alt="facebook" class="redes_sociales"> Facebook</li>
                        <li><img src="img/fooder/instagram.png" alt="instagram" class="redes_sociales">Instagram</li>
                        <li><img src="img/fooder/twitter.png" alt="twitter" class="redes_sociales">Twiter</li>
                        <li><img src="img/fooder/whatsapp.png" alt="whatsapp" class="redes_sociales">Whatsapp</li>
                    </ul>     
                </article>
                <br>     
            </div>
            <div class="copyright">
                    <p class="copyroght">
                            © ELIMAR - Todos los Derechos Reservados 2019
                    </p>
            </div>
        </footer>

        @yield('fieldjs')
</body>
</html>

resources/views/layoutDescripcion.blade.php
 <!DOCTYPE html>
<html lang="en">
<head>

    @yield('headers')
    
</head>
<body>
  <header>
        <div class="contenedor_navbar">
            <div class="contenedor_animada">
                <ul>
                    <li>
                        <h1 class="h1">US$3 </h1> DESCUENTO DE SU PRIMERA ORDEN
                    </li>
                    <li>
                        <h1 class="h1">US$3 </h1> DESCUENTA DE ROPA DE VERANO
                    </li>
                </ul>
            </div>
            <a href="{{route('index')}}" class="navbar_logo">
                <img src="../../img/logo.png" alt="Logo">
            </a>
            <input type="checkbox" id="menu_navbar">
            <label for="menu_navbar">
                <img src="../../img/menu.png" alt="menu">
            </label>
            <nav class="menu_nav">
                <ul class="menu_principal">
                    <li class="menu_lista">
                        <div class="container_1">
                            <form action="" autocomplete="on">
                                <input id="search" name="search" type="text" placeholder="Buscar..." class="search">
                                <input type="submit" id="search_submit" value="Buscar">
                            </form>
                        </div>
                    </li>
                    <li class="menu_lista">
                        <a href="{{ route('prendas')}}">Prendas <img src="../../img/arrow.png" alt="arrow"></a>
                    </li>
                    <li class="menu_lista sub_cuenta">
                        <a href="#" class="cuenta">Cuenta <span class="fas fa-sort-down"></span></a>
                        <ul class="sub_menu">
                            @guest
                            <li class="menu_lista">
                                <a href="{{route('login')}}">Iniciar Sesion <img src="../../img/arrow.png" alt="arrow"></a>
                            </li>
                             <li class="menu_lista">
                                <a href="{{route('compras')}}">Compras <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('resenas.index')}}">Reseñas <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            @else

                            <li class="menu_lista">
                                <a href="#"><?php echo explode(" ",Auth::user()->name)[0]; ?> <img src="../../img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('compras')}}">Compras <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('resenas.index')}}">Reseñas <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a  href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Salir
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                            </li>

                            @if(Auth::user()->role=='admin')

                            <li class="menu_lista">
                                <a href="{{route('prendas')}}">Administrar <img src="../../img/arrow.png" alt="arrow"></a>
                            </li>


                            @endif


                            @endguest
                        </ul>
                    </li>
                    <li class="menu_lista_2">
                        <a href="{{route('carrito')}}">Carrito de Compra <img src="../../img/arrow.png" alt="arrow"></a>
                    </li>
                    <li class="menu_lista_3">
                        <a href="{{route('carrito')}}"><span class="fas fa-shopping-cart"></span></a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>



            @yield('main')



                <footer>
            <div class="politica">
                    <h1>Politicas de la Tienda</h1> 
                    <br>
                    <article>
                        <ul>
                            <li>Términos y condiciones</li>
                            <li>Horario de Atención</li>
                            <li>Libro de Reclamos</li>
                            <li>Políticas de entrega , garantía y devolución</li>
                        </ul>
                    </article> 
                    <br>   
            </div>
            <div class="tienda">
                    <h1>Información de la Tienda</h1> 
                    <br>
                    <article>
                        <ul>
                            <li>Tienda   Elimar</li>
                            <li>Llámanos ahora al: 951 545 421</li>
                            <li>Email: elimar@gmail.com</li>
                        </ul> 
                    </article>
                    <br>
            </div>
            <div class="redes">
                <h1>Redes Sociales</h1> 
                <br>
                <article>
                    <ul>
                        <li><img src="../../img/fooder/facebook.png" alt="facebook" class="redes_sociales"> Facebook</li>
                        <li><img src="../../img/fooder/instagram.png" alt="instagram" class="redes_sociales">Instagram</li>
                        <li><img src="../../img/fooder/twitter.png" alt="twitter" class="redes_sociales">Twiter</li>
                        <li><img src="../../img/fooder/whatsapp.png" alt="whatsapp" class="redes_sociales">Whatsapp</li>
                    </ul>     
                </article>
                <br>     
            </div>
            <div class="copyright">
                    <p class="copyroght">
                            © ELIMAR - Todos los Derechos Reservados 2019
                    </p>
            </div>
        </footer>

        @yield('fieldjs')
</body>
</html>

resources/views/layoutShow.blade.php
 <!DOCTYPE html>
<html lang="en">
<head>

    @yield('headers')
    
</head>
<body>
  <header>
        <div class="contenedor_navbar">
            <div class="contenedor_animada">
                <ul>
                    <li>
                        <h1 class="h1">US$3 </h1> DESCUENTO DE SU PRIMERA ORDEN
                    </li>
                    <li>
                        <h1 class="h1">US$3 </h1> DESCUENTA DE ROPA DE VERANO
                    </li>
                </ul>
            </div>
            <a href="{{route('index')}}" class="navbar_logo">
                <img src="../img/logo.png" alt="Logo">
            </a>
            <input type="checkbox" id="menu_navbar">
            <label for="menu_navbar">
                <img src="../img/menu.png" alt="menu">
            </label>
            <nav class="menu_nav">
                <ul class="menu_principal">
                    <li class="menu_lista">
                        <div class="container_1">
                            <form action="" autocomplete="on">
                                <input id="search" name="search" type="text" placeholder="Buscar..." class="search">
                                <input type="submit" id="search_submit" value="Buscar">
                            </form>
                        </div>
                    </li>
                    <li class="menu_lista">
                        <a href="{{ route('prendas')}}">Prendas <img src="../img/arrow.png" alt="arrow"></a>
                    </li>
                    <li class="menu_lista sub_cuenta">
                        <a href="#" class="cuenta">Cuenta <span class="fas fa-sort-down"></span></a>
                        <ul class="sub_menu">
                            @guest
                            <li class="menu_lista">
                                <a href="{{route('login')}}">Iniciar Sesion <img src="../img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('compras')}}">Compras <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('resenas.index')}}">Reseñas <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            @else

                            <li class="menu_lista">
                                <a href="#"><?php echo explode(" ",Auth::user()->name)[0]; ?> <img src="../img/arrow.png" alt="arrow"></a>
                            </li>
                             <li class="menu_lista">
                                <a href="{{route('compras')}}">Compras <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a href="{{route('resenas.index')}}">Reseñas <img src="img/arrow.png" alt="arrow"></a>
                            </li>
                            <li class="menu_lista">
                                <a  href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Salir
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                            </li>

                            @if(Auth::user()->role=='admin')

                            <li class="menu_lista">
                                <a href="{{route('prendas')}}">Administrar <img src="../img/arrow.png" alt="arrow"></a>
                            </li>


                            @endif


                            @endguest
                        </ul>
                    </li>
                    <li class="menu_lista_2">
                        <a href="{{route('carrito')}}">Carrito de Compra <img src="../img/arrow.png" alt="arrow"></a>
                    </li>
                    <li class="menu_lista_3">
                        <a href="{{route('carrito')}}"><span class="fas fa-shopping-cart"></span></a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>



            @yield('main')



                <footer>
            <div class="politica">
                    <h1>Politicas de la Tienda</h1> 
                    <br>
                    <article>
                        <ul>
                            <li>Términos y condiciones</li>
                            <li>Horario de Atención</li>
                            <li>Libro de Reclamos</li>
                            <li>Políticas de entrega , garantía y devolución</li>
                        </ul>
                    </article> 
                    <br>   
            </div>
            <div class="tienda">
                    <h1>Información de la Tienda</h1> 
                    <br>
                    <article>
                        <ul>
                            <li>Tienda   Elimar</li>
                            <li>Llámanos ahora al: 951 545 421</li>
                            <li>Email: elimar@gmail.com</li>
                        </ul> 
                    </article>
                    <br>
            </div>
            <div class="redes">
                <h1>Redes Sociales</h1> 
                <br>
                <article>
                    <ul>
                        <li><img src="../img/fooder/facebook.png" alt="facebook" class="redes_sociales"> Facebook</li>
                        <li><img src="../img/fooder/instagram.png" alt="instagram" class="redes_sociales">Instagram</li>
                        <li><img src="../img/fooder/twitter.png" alt="twitter" class="redes_sociales">Twiter</li>
                        <li><img src="../img/fooder/whatsapp.png" alt="whatsapp" class="redes_sociales">Whatsapp</li>
                    </ul>     
                </article>
                <br>     
            </div>
            <div class="copyright">
                    <p class="copyroght">
                            © ELIMAR - Todos los Derechos Reservados 2019
                    </p>
            </div>
        </footer>

        @yield('fieldjs')
</body>
</html>