routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('index');
// });

Route::resource('/','indexController');


Route::get('/direccion/{id}','direccionController');


Route::get('/galeria/{id?}','prendasController@mostrar')->name('prendas');

// Route::view('/galeria','prendas')->name('prendas');

// Route::view('/prendaDescripcion','prendaDetails')->name('prendaDetails');

Route::get('/prendaDescripcion/{id?}/{color?}','descripcionController')->name('prendaDescripcion');


Route::get('/contraEntrega','contraEntregaController')->name('contraEntrega')->middleware('verified');


Route::get('/obtenerComentarios/{id?}','getComentariosController')->name('getComentarios');
// Route::get('/contraEntrega')

Route::view('/cart','carrito')->name('carrito');




Route::resource('/resenas','resenasController')->middleware('verified');


Route::get('/compras','comprasController')->name('compras')->middleware('verified');


Route::get('/detalle/{id?}','comprasController@detalles')->name('detalle');





Route::view('/pagoTarjeta','pagoTarjeta')->name('pagoTarjeta');


Route::view('/transferencia','transferencia')->name('transferencia');





// Route::get('/tipoPrenda',function(){
// 	return view('cms.formaPago');
// });


Route::resource('/comentarios','comentariosController');

Route::resource('/talla','tallaController');


Route::resource('/tipoPrenda','tipoPrendaController');


Route::resource('/formaPago','formaPagoController');

Route::resource('/estadoVenta','estadoVentaController');

Route::resource('/ventas','ventasController');





Route::resource('/prenda','prendaController');


Route::resource('/color','colorController');

Route::resource('/imagen','imagenController');




// RUTAS DE CONSULTA

Auth::routes(['verify'=> true]);


Route::get('/dataTalla','dataTallaController');


Route::get('/dataTipo','dataTipoController');


Route::get('/dataColor/{id}','dataColorController');



//FIN RUTAS DE CONSULTA


// Route::view('/tipoPrenda','cms.tipoPrenda')->name('cms.tipoPrenda');

// Route::view('/formaPago','cms.formaPago')->name('cms.formaPago');

// Route::view('/estadosVenta','cms.estadosVenta')->name('cms.estadoVenta');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');




Route::get('/ventasDetalle/{id}','detallesController');

resources/views/cms/estadosVenta.blade.php
@extends('cms.layout')


@section('content')


<div class="registrar caja">
	<h1 class="titulos">Registrar Estados Venta</h1>
	

	<form method="POST" action="{{route('estadoVenta.store')}}">
		@csrf
		<input type="text" placeholder="Estado" name="estado"><br>

		<textarea name="descripcion" placeholder="Descripcion"></textarea> 

		<input type="submit" name="">

	</form>
	

</div>






<div class="tabla-pos2 caja-lg">
	<h1 class="titulos">Estados Venta</h1>

	<table class="tabla-lista">
		<thead>
			<tr><th>Id</th> <th>Estados Venta</th> <th>Descripcion</th></tr>
		</thead>
		<tbody>
			@forelse($estadoVenta as $listar)

			  @if($listar->state)

			<tr><td>{{$listar->id}}</td><td>{{$listar->estado}}</td><td>{{$listar->descripcion}}</td><td class="actualizar"><button key="{{$listar->id}}" catalogo="talla"  class="editar-modal">Editar</button></td><td  class="eliminar"><form method="POST" action="{{route('estadoVenta.destroy',$listar->id)}}">
				@csrf
				{!! method_field('DELETE') !!}
				<button type="submit">eliminar</button></form></td></tr>

			  @endif
			@empty

			<tr><td>vacio</td><td>vacio</td><td>vacio</td><td class="actualizar"><button class="editar-modal">Editar</button></td><td class="eliminar"><button>eliminar</button></td></tr>

			@endforelse
		</tbody>
	</table>
	

</div>
@include('cms.partials.modalEstadoVenta')

@endsection


@section('enlacesjs')

<script type="text/javascript" src="js/cms/estadoVenta.js"> </script>

@endsection

resources/views/cms/formaPago.blade.php
@extends('cms.layout')


@section('content')

<div class="registrar caja">
	<h1 class="titulos">Registrar Forma de pago</h1>

	<form method="POST" action="{{route('formaPago.store')}}">
		@csrf
		<input type="text" placeholder="forma de pago" name="fpago"><br>

		<textarea name="descripcion" placeholder="Descripcion"></textarea> 

		<input type="submit" name="">

	</form>
	

</div>


<div class="tabla-pos2 caja-lg">
	<h1 class="titulos">Formas de pago</h1>

	<table class="tabla-lista">
		<thead>
			<tr><th>Id</th> <th>Forma Pago</th> <th>Descripcion</th></tr>
		</thead>
		<tbody>
		@forelse($formaPago as $listar)

			  @if($listar->state)

			<tr><td>{{$listar->id}}</td><td>{{$listar->fpago}}</td><td>{{$listar->descripcion}}</td><td class="actualizar"><button key="{{$listar->id}}" catalogo="talla"  class="editar-modal">Editar</button></td><td  class="eliminar"><form method="POST" action="{{route('formaPago.destroy',$listar->id)}}">
				@csrf
				{!! method_field('DELETE') !!}
				<button type="submit">eliminar</button></form></td></tr>

			  @endif
			@empty

			<tr><td>vacio</td><td>vacio</td><td>vacio</td><td class="actualizar"><button class="editar-modal">Editar</button></td><td class="eliminar"><button>eliminar</button></td></tr>

			@endforelse
		</tbody>
	</table>
	

</div>

@include('cms.partials.modalFormaPago')

@endsection

@section('enlacesjs')

<script type="text/javascript" src="js/cms/formaPago.js"> </script>

@endsection

resources/views/cms/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>CMS</title>
	<link rel="stylesheet" type="text/css" href="css/cms/reset.css">
	<link rel="stylesheet" type="text/css" href="css/cms/header.css">
	
	<link rel="stylesheet" type="text/css" href="css/cms/estilosElimar.css">
	<link rel="stylesheet" type="text/css" href="css/cms/aside.css">
	<link rel="stylesheet" type="text/css" href="css/cms/contenido.css">
	<link rel="stylesheet" type="text/css" href="css/cms/talla.css">
	<link rel="stylesheet" type="text/css" href="css/cms/mdlPrendaStock.css">
	<link rel="stylesheet" type="text/css" href="css/cms/mdlPrendaAgregar.css">
	<link rel="stylesheet" type="text/css" href="css/cms/mdlPrendaImagenes.css">
	<link rel="stylesheet" type="text/css" href="css/cms/mdlPrendaEditar.css">
	<link rel="stylesheet" type="text/css" href="css/cms/ventas.css">
</head>
<body>


{{-- contenido GESTOR --}}

<aside>


	<div>
		<img src="iconos/elimaricon.jpg" >
	</div>

	<div>

		<div id="opciones">
			<h1>Gestion</h1>

				<ul>
					<a href="{{route('ventas.index')}}"><li>Venta<img  src="iconos/circle-outline.png"></li> </a>
					<a href="{{route('prenda.index')}}"><li>Prenda<img  src="iconos/circle-outline.png"></li></a>
					<a href=""><li>Usuarios<img  src="iconos/circle-outline.png"></li></a>
					<a href=""><li>Comentarios<img  src="iconos/circle-outline.png"></li></a>
				</ul>

			
		</div>

				
        <div id="opciones">
			<h1>Configuracion</h1>

				<ul>
					<a href="{{route('tipoPrenda.index')}}"><li>Tipo Prenda<img  src="iconos/circle-outline.png"></li></li></a>
					<a href="{{route('talla.index')}}"><li>Tallas<img  src="iconos/circle-outline.png"></li></a>
					<a href="{{route('formaPago.index')}}"><li>Forma Pago<img  src="iconos/circle-outline.png"></li></a>
					<a href="{{route('estadoVenta.index')}}"><li>Estados Venta<img  src="iconos/circle-outline.png"></li></a>
				</ul>

			
		</div>
				 
		
	</div>




	
</aside>

<section id="contenido">

	<header>
	
   </header>


  <section id="main">

  	@yield('content')
	
  </section>
	

	
</section>



   @yield('enlacesjs')

{{-- FIN GESTOR --}}




</body>
</html>

resources/views/cms/prenda.blade.php
@extends("cms.layout")



@section('content')



<div> <button id="btn-agregar" class="btn-agregar">agregar</button></div>




<div class="tabla-pos1 caja-lg">
	<h1 class="titulos">Prendas</h1>

	<table class="tabla-lista">
		<thead>
			<tr><th>Id</th> <th>Tipo</th> <th>Nombre</th><th>Descripcion</th><th>Costo</th></tr>
		</thead>
		<tbody>

			@forelse($prendas as $listar)

			
			<tr><td>{{$listar->id}}</td><td>{{$listar->tipo->tipo}}</td><td>{{$listar->nombre}}</td><td>{{$listar->descripcion}}</td><td>{{$listar->precio}}</td><td key="{{$listar->id}}"  id="btn-stock" class="actualizar btn-stock"><button>stock</button></td><td class="actualizar"><button key="{{$listar->id}}" tipo="{{$listar->tipo->tipo}}" id="btn-imagenes" class="btn-imagenes" >imagenes</button></td><td><button key="{{$listar->id}}" class="btn-Editar" id="btn-Editar">editar</button></td></tr>


			@empty

			 <tr><td>vacio</td><td>vacio</td><td>vacio</td><td>vacio</td><td>vacio</td><td id="btn-stock" class="actualizar"><button>stock</button></td><td class="actualizar"><button id="btn-imagenes" class="btn-imagenes" >imagenes</button></td><td><button id="btn-Editar">editar</button></td></tr>

			 @endforelse


		</tbody>
	</table>
	

</div>

@include('cms.partials.modalPrendaStock')

@include('cms.partials.modalPrendaAgregar')

@include('cms.partials.modalPrendaImagenes')

@include('cms.partials.modalPrendaEditar')

@endsection

@section('enlacesjs')




<script type="text/javascript" src="js/cms/prendaStock.js"> </script>

<script type="text/javascript" src="js/cms/prendaTipo.js"> </script>

<script type="text/javascript" src="js/cms/prenda.js"> </script>


@endsection

resources/views/cms/talla.blade.php
@extends("cms.layout")


@section('content')



<div class="registrar caja">
	<h1 class="titulos">Registrar Tallas</h1>

	<form method="post" action="{{route('talla.store')}}">
		@csrf

		<input type="text" placeholder="talla" name="talla"><br>

		<input type="text" placeholder="descripcion" name="descripcion"><br>

		<input type="submit" name="">

	</form>
	

</div>






<div class="tabla-pos2 caja-lg">
	<h1 class="titulos">Tallas</h1>

	<table class="tabla-lista">
		<thead>
			<tr><th>Id</th> <th>Talla</th> <th>Descripcion</th></tr>
		</thead>
		<tbody>

			@forelse($talla as $tallas)

			  @if($tallas->state)

			<tr><td>{{$tallas->id}}</td><td>{{$tallas->talla}}</td><td>{{$tallas->descripcion}}</td><td class="actualizar"><button key="{{$tallas->id}}" catalogo="talla"  class="editar-modal">Editar</button></td><td  class="eliminar"><form method="POST" action="{{route('talla.destroy',$tallas->id)}}">
				@csrf
				{!! method_field('DELETE') !!}
				<button type="submit">eliminar</button></form></td></tr>

			  @endif
			@empty

			<tr><td>vacio</td><td>vacio</td><td>vacio</td><td class="actualizar"><button class="editar-modal">Editar</button></td><td class="eliminar"><button>eliminar</button></td></tr>

			@endforelse
			
		</tbody>
	</table>
	

</div>


@include('cms.partials.modalTalla')
@endsection

@section('enlacesjs')

<script type="text/javascript" src="js/cms/talla.js"> </script>

@endsection

resources/views/cms/tipoPrenda.blade.php
@extends('cms.layout')



@section('content')



<div class="registrar caja">
	<h1 class="titulos">Registrar Tipo Prenda</h1>

	<form method="POST" action="{{route('tipoPrenda.store')}}">

		@csrf
		<input type="text" placeholder="tipo prenda" name="tipo"><br>

		<textarea name="descripcion" placeholder="descripcion"></textarea>

		<input type="submit" name="">

	</form>
	

</div>






<div class="tabla-pos2 caja-lg">
	<h1 class="titulos">Tipo Prenda</h1>

	<table class="tabla-lista">
		<thead>
			<tr><th>Id</th> <th>Tipo Prenda</th> <th>Descripcion</th></tr>
		</thead>
		<tbody>
			@forelse($tipoPrenda as $listar)

			  @if($listar->state)

			<tr><td>{{$listar->id}}</td><td>{{$listar->tipo}}</td><td>{{$listar->descripcion}}</td><td class="actualizar"><button key="{{$listar->id}}" catalogo="talla"  class="editar-modal">Editar</button></td><td  class="eliminar"><form method="POST" action="{{route('tipoPrenda.destroy',$listar->id)}}">
				@csrf
				{!! method_field('DELETE') !!}
				<button type="submit">eliminar</button></form></td></tr>

			  @endif
			@empty

			<tr><td>vacio</td><td>vacio</td><td>vacio</td><td class="actualizar"><button class="editar-modal">Editar</button></td><td class="eliminar"><button>eliminar</button></td></tr>

			@endforelse
		</tbody>
	</table>
	

</div>


@include('cms.partials.modalTipoPrenda')

@endsection


@section('enlacesjs')

<script type="text/javascript" src="js/cms/tipoPrenda.js"> </script>

@endsection

resources/views/cms/ventas.blade.php
@extends('cms.layout')



@section('content')


                      <div class="buscadorVentas"><label>Buscar por</label><select id="buscadorVentas">
	                         <option>--selecione--</option>
	                         <option value="desc">nuevos</option>
	                         <option value="asc">antiguo</option>
	                           
                            </select>
                        </div>


                            <div  class="selectDate">
                            	<form method="get" action="http://creaciones.test/ventas">
                            		
                            	
                            	<label>DESDE: </label><input type="date" name="from" value="">

                            	<label>HASTA: </label><input type="date" name="to" value="">


                            	<button type="submit">Buscar</button>

                            	</form>
                            </div>


<div>
	<h1 class="titulos">Ventas</h1>

	<table class="tabla-ventas">
		<thead>
			<tr><th>Id</th> <th>Cliente</th> <th>Fecha</th><th>Importe</th><th>Costo Envio</th><th>Total</th><th>Forma Pago</th><th>Estado</th><th></th><th></th><th></th></tr>
		</thead>
		<tbody>


			@forelse($contenido as $listar)

			
            
			 <tr><td>{{$listar->id}}</td><td>{{$listar->user->name}}</td><td>{{$listar->created_at}}</td><td>{{$listar->total}}</td><td>{{$listar->cenv}}</td><td>{{$listar->totalp}}</td><td>{{$listar->forma_pago->fpago}}</td><td > 
			 	@csrf
			 	<select key="{{$listar->id}}" class="estadoPedido">

			 		@forelse($estados as $listado)

			 		@if($listado->id == $listar->estado->id)

			 		  <option selected="selected" value="{{$listado->id }}">{{$listado->estado}}</option>

			 		 @else

			 		 <option value="{{$listado->id }}">{{$listado->estado}}</option>

			 		 @endif



			 		
			 		@empty
			 		<option>vacio</option>

			 		@endforelse

			 	</select></td>

			 	<td><button  key={{$listar->id}} class="venta-direccion">direccion</button></td><td><button key={{$listar->id}} user={{$listar->user->id}} class="venta-ver">ver</button></td><td><form method="POST" action="http://creaciones.test/ventas/{{$listar->id}}">
			 		 @csrf
			 		 {!! method_field('DELETE') !!}

			 		<button type="submit" class="venta-eliminar">eliminar</button>
			 		
			 	</form>
			 		</td></tr>

			{{--  <tr><td>vacio</td><td>cristian alvarez</td><td>vacio</td><td>vacio</td><td>vacio</td><td>vacio</td><td>vacio</td><td ><select></select></td><td><button>direccion</button></td><td><button>ver</button></td><td><button>eliminar</button></td></tr>
 --}}         @empty


              <tr><td>vacio</td><td>cristian alvarez</td><td>vacio</td><td>vacio</td><td>vacio</td><td>vacio</td><td>vacio</td><td ><select></select></td><td><button>direccion</button></td><td><button>ver</button></td><td><button>eliminar</button></td></tr>


             @endforelse

		</tbody>
	</table>

	<div>
		{{$contenido->links()}}
	</div>
	

</div>



<div id="cajaVentas" class="cajaVentas">
	<div  id="ventaDireccionModal" class="modal-into">

		<div>
			<h2></h2>
			<label></label>
		</div>


		<div>
			<h2></h2>
			<label></label>
		</div>

		<div>
			<h2></h2>
			<label></label>
		</div>


		<div>
			<h2></h2>
			<label></label>
		</div>


		<div>
			<h2></h2>
			<label></label>
		</div>


		<div>
			<h2></h2>
			<label></label>
		</div>
		
	</div>
</div>


<div id="modalDetalleVenta" class="modalDetalleVenta">



	<div  id="DetalleVentaContenido" class="contenidoModal">


		<div class="pulpa">

			<div>
				<img src="../img/Ropa/large.jpg" width="180px">
			</div>

			<div>

				<div>

				<label>
				<h2>Diseño:&nbsp;</h2>

				pantalo rayas

				</label>

				<label>
					<h2>Talla:&nbsp;</h2>
					S
					
				</label>

				</div>

				<div>
				<label>
					<h2>Cantidad:&nbsp;</h2>
					1
					
				</label>

				<label>
					<h2>Color:&nbsp;</h2>
                       ROSADO
				</label>
				</div>

				<div>
					
				<label>
					<h2>Precio:&nbsp;</h2>

					S/.20.00
					
				</label>
				<label>
					<h2>Total:&nbsp;</h2>

					S/.20.00
					
				</label>

				</div>
			</div>

			
			

		</div>


		<div class="pulpa">

			<div>
				<img src="../img/Ropa/large.jpg" width="180px">
			</div>

			<div>

				<div>

				<label>
				<h2>Diseño:&nbsp;</h2>

				pantalo rayas

				</label>

				<label>
					<h2>Talla:&nbsp;</h2>
					S
					
				</label>

				</div>

				<div>
				<label>
					<h2>Cantidad:&nbsp;</h2>
					1
					
				</label>

				<label>
					<h2>Color:&nbsp;</h2>
                       ROSADO
				</label>
				</div>

				<div>
					
				

				<label>
					<h2>Precio:&nbsp;</h2>

					S/.20.00
					
				</label>
				<label>
					<h2>Total:&nbsp;</h2>

					S/.20.00
					
				</label>

				</div>
				
			</div>

			
			

		</div>
		
		



	</div>
	


</div>





@endsection


@section('enlacesjs')

<script type="text/javascript" src="js/cms/ventas.js"> </script>

@endsection